env:
  browser: true
  es2021: true
  node: true
extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended']
parser: '@typescript-eslint/parser'
root: true
ignorePatterns: ["oldsrc/", "tests/mod.test.ts", "tests/index.test.ts"]
rules:
  no-constant-condition: 'off'
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - argsIgnorePattern: '_.*'
      varsIgnorePattern: '_.*'
  '@typescript-eslint/no-explicit-any': 'off'
