const fs = require("fs");
const crypto = require("crypto");

async function main() {
  const tsPath = "src/runtime.ts";

  const kernelPath = "wasm/extism-runtime.wasm";
  const kernelContents = await fs.promises.readFile(kernelPath);
  const kernelBase64 = kernelContents.toString("base64");
  const kernelHash = await crypto.createHash("sha256").update(kernelContents)
    .digest("hex");

  await fs.promises.writeFile(tsPath, `// DO NOT EDIT - this file was generated by update-kernel.js\nexport const embeddedRuntime = '${kernelBase64}';\nexport const embeddedRuntimeHash = '${kernelHash}';`);
}

main();
